#########################
##  SNAKEFILE SAMPLES  ##
#########################
samples:
  ERR696683_chr5_1: data/raw/ERR696683_chr5_1.fastq.gz
  ERR696683_chr5_2: data/raw/ERR696683_chr5_2.fastq.gz
  ERR753368_chr5_1: data/raw/ERR753368_chr5_1.fastq.gz
  ERR753368_chr5_2: data/raw/ERR753368_chr5_2.fastq.gz
  ERR753369_chr5_1: data/raw/ERR753369_chr5_1.fastq.gz
  ERR753369_chr5_2: data/raw/ERR753369_chr5_2.fastq.gz
  ERR753370_chr5_1: data/raw/ERR753370_chr5_1.fastq.gz
  ERR753370_chr5_2: data/raw/ERR753370_chr5_2.fastq.gz
  ERR753371_chr5_1: data/raw/ERR753371_chr5_1.fastq.gz
  ERR753371_chr5_2: data/raw/ERR753371_chr5_2.fastq.gz
  ERR753372_chr5_1: data/raw/ERR753372_chr5_1.fastq.gz
  ERR753372_chr5_2: data/raw/ERR753372_chr5_2.fastq.gz
  ERR753373_chr5_1: data/raw/ERR753373_chr5_1.fastq.gz
  ERR753373_chr5_2: data/raw/ERR753373_chr5_2.fastq.gz
  ERR753374_chr5_1: data/raw/ERR753374_chr5_1.fastq.gz
  ERR753374_chr5_2: data/raw/ERR753374_chr5_2.fastq.gz
  ERR753375_chr5_1: data/raw/ERR753375_chr5_1.fastq.gz
  ERR753375_chr5_2: data/raw/ERR753375_chr5_2.fastq.gz
  ERR753376_chr5_1: data/raw/ERR753376_chr5_1.fastq.gz
  ERR753376_chr5_2: data/raw/ERR753376_chr5_2.fastq.gz
  ERR753377_chr5_1: data/raw/ERR753377_chr5_1.fastq.gz
  ERR753377_chr5_2: data/raw/ERR753377_chr5_2.fastq.gz
  ERR753378_chr5_1: data/raw/ERR753378_chr5_1.fastq.gz
  ERR753378_chr5_2: data/raw/ERR753378_chr5_2.fastq.gz

########################
##  SNAKEFILE PARAMS  ##
########################

## Choose your chromosome
chromosome: chr5
# Basically the url of a chromosome in this analysis
url_reference_genome: https://ftp.ensembl.org/pub/release-109/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.chromosome.5.fa.gz

## Fixing the fastq files, FASTP parameters:
fastp_cuttail: 30
fastp_cutfront: 30
fastp_cutmeanq: 30
fastp_length: 75

## Termination of your the reads, i wrote these params in case they
## could be _1/_2, or others like _R1/_R2 for example
reads_forward_termination: _1
reads_reverse_termination: _2

## Extracting variants
ref_genome_name_file: genome.fa
# Min reads that has to be mapping to considerate a variant
min_reads_variant: 30

## Doing VEP for variant annotation
vep_species: homo_sapiens
vep_assembly: GRCh38
  
