name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Chromosome 3 workflow
        run: |
          cat config.yaml
      - name: chromosome 5 workflow
        run: |
          sed -i '6,+12s/chr3/chr5/g config.yaml
          sed -i '24,+12s/chr3/chr5/g' config.yaml
          sed -i '39s/chr3/chr5/g' config.yaml
          sed -i '46s/chromosome.3.fa.gz/chromosome.5.fa.gz/g' config.yaml
          sed -i '65s/PIK3CA/APC/g config.yaml
          cat config.yaml
      - name: chromosome 7 workflow
        run: |
          sed -i '6,+12s/chr5/chr7/g config.yaml
          sed -i '24,+12s/chr5/chr7/g' config.yaml
          sed -i '39s/chr5/chr7/g' config.yaml
          sed -i '46s/chromosome.5.fa.gz/chromosome.7.fa.gz/g' config.yaml
          sed -i '65s/APC/BRAF/g config.yaml
          cat config.yaml
      - name: chromosome 12 workflow
        run: |
          sed -i '6,+12s/chr7/chr12/g config.yaml
          sed -i '24,+12s/chr7/chr12/g' config.yaml
          sed -i '39s/chr7/chr12/g' config.yaml
          sed -i '46s/chromosome.7.fa.gz/chromosome.12.fa.gz/g' config.yaml
          sed -i '65s/BRAF/KRAS/g config.yaml
          cat config.yaml
      - name: chromosome 5 workflow
        run: |
          sed -i '6,+12s/chr12/chr17/g config.yaml
          sed -i '24,+12s/chr12/chr17/g' config.yaml
          sed -i '39s/chr12/chr17/g' config.yaml
          sed -i '46s/chromosome.12.fa.gz/chromosome.17.fa.gz/g' config.yaml
          sed -i '65s/KRAS/TP53/g config.yaml
          cat config.yaml
      - run: echo "🍏 This job's status is ${{ job.status }}."
